language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm test
  - npm run build
deploy:
  - provider: script
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    target_branch: gh-pages
    on:
      branch: master